### ISSUE TITLE
Error during MQTT data

### ISSUE THREAD

**Issue by racleave** [hammockman/breather#22]
While running overnight (>6000 breaths) the following error resulted. Probably not worrying about now, except to report further incidences here.

```
Traceback (most recent call last):
  File "breathe.py", line 73, in <module>
p
    M.publish('breathe/sensors/current', json.dumps(deque2dict(S.current_values)), retain=True)
  File "breathe.py", line 38, in deque2dict
    for d in q:
RuntimeError: deque mutated during iteration
pi@manawa-ora-1:~/breather/Design/Final/Code $ 
```

**Comment by hammockman** [comment]
Fixed in 3560a4a
