### ISSUE TITLE
Smbus failure

### ISSUE THREAD

**Issue by racleave** [hammockman/breather#23]
There were some errors using write_byte yesterday (from bmp085.py).

Not a major worry now - this issue is just for reporting further occurrences (need to copy error messages next time!).

**Comment by racleave** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/breather/Design/Final/Code/sensors.py", line 109, in run
    self.current_values.append(read_all())
  File "/home/pi/breather/Design/Final/Code/sensors.py", line 58, in read_all
    p_h, t_h = bmp085_h.read()
  File "/home/pi/breather/Design/Final/Code/bmp085.py", line 62, in read
    self.write_byte(0xF4, 0x34 + (self.oss << 6))
  File "/home/pi/breather/Design/Final/Code/bmp085.py", line 51, in write_byte
    self.bus.write_byte_data(self.address, offset, value)
OSError: [Errno 121] Remote I/O error

**Comment by racleave** [comment]
Looks like it might be a wiring issue. TBC.
